<a href="https://colab.research.google.com/github/Kinza205/Syntecxhub_Project_Task_1/blob/main/Project_No_1_NumPy_Data_Explorer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time

print("===== NUMPY DATA EXPLORER =====\n")

===== NUMPY DATA EXPLORER =====



In [2]:
# 1 Array Creation
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

Original Array: [10 20 30 40 50]


In [4]:
# 2 Indexing & Slicing
print("\nIndexing:")
print("First element:", arr[0])
print("Last element:", arr[-1])
print("\nSlicing:")
print("First 3 elements:", arr[:3])


Indexing:
First element: 10
Last element: 50

Slicing:
First 3 elements: [10 20 30]


In [5]:
# 3 Mathematical Operations
print("\nMathematical Operations:")
print("Add 5:", arr + 5)
print("Square:", arr ** 2)


Mathematical Operations:
Add 5: [15 25 35 45 55]
Square: [ 100  400  900 1600 2500]


In [6]:
# 4 Axis-wise / 2D Operations
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("\nMatrix:\n", matrix)
print("Sum of columns:", matrix.sum(axis=0))
print("Sum of rows:", matrix.sum(axis=1))



Matrix:
 [[1 2 3]
 [4 5 6]]
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]


In [7]:
# 5 Statistical Operations
print("\nStatistics:")
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))


Statistics:
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [8]:
# 6 Reshaping
reshaped = np.arange(1, 10).reshape(3, 3)
print("\nReshaped Array (3x3):\n", reshaped)


Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# 7 Broadcasting
print("\nBroadcasting Example:")
print(reshaped + 10)


Broadcasting Example:
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [10]:
# 8 Save & Load Array
np.save("my_array.npy", arr)
loaded_arr = np.load("my_array.npy")
print("\nLoaded Array:", loaded_arr)


Loaded Array: [10 20 30 40 50]


In [11]:
# 9 Performance Comparison
print("\nPerformance Comparison:")

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python List Time:", end - start)

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result_np = arr1 + arr2
end = time.time()
print("NumPy Time:", end - start)

print("\n===== END =====")


Performance Comparison:
Python List Time: 0.05053901672363281
NumPy Time: 0.003216266632080078

===== END =====
